# Generated by Django 3.0.5 on 2020-04-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('U_ID', models.TextField()),
                ('Name', models.TextField()),
            ],
        ),
    ]
